language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=http://localhost:8080
  - PACT_BROKER_BASE_URL=https://throwaway.pact.dius.com.au
  # PACT_BROKER_TOKEN is encrypted below
  - secure: NWtYVIO4XIzyKwL/qnGLT2iBxvOfZFyK545LqOPzyzkb1o9rpO0f2TG8jM+m2QeFNgYriTwsfYZg91MGpyLZeCUPPfCtjN07/VFJ3XJ+fGqaKYgXBJnwfQu1QtiIvcVgAEj91CRkmSIL/MafoYKcpIiZjeXZyuFvJN2QJ0NctsV1gbuS+pKgXgxjYRs5IhiBlwhBtPQa2eshy3+1rFUOq7S8TIqwzxVHQq7mO5If6epYN5GbCwgkGNFilRZqevHrHIwkzcw8gsasFOr+umdRCoRRjISyuA/arccN0eO/ylUZnAMfgEBi8Nk9fn9RPhV8PcWwDhIEo/cqY0uGrx7RnZpC1l581FSmF3kc9LGdhOaCwVpfch9Xfdh1Wmn4y9tcRKdIeAH6R6JbPgd23WGfwAY45yr8+L9qtQYdV0VxzTlC8jn3Q8KaoacPdVIRZqiGFsNwNF3fTEJsnpyws7rfGd4PdflMdoVasowjXTPXzmnFNsiqfwGDngoJP6X0OSrskBn1UpIehqVphvsO9Rv8qjjmzR21uB8F8P687sf6JJTJXGuStH3mn+NAzdc0ieniWqIoxsK35YfCll8Q+bblBskQkJMVbE2j+iCkKhhbymVJre/EriY6MBUChEjtkPHctdHmXqVnkpzZf5xvs+Oua/NflPYOrRyUgT+qWAegKUk=
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
